stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - cifar10
  train:
    cmd: python main.py
    deps:
    - cifar10
    - modeling
    - conf
    outs:
    - ddpm.pt