run_name: "Hydra default"
model:
  img_channels: 3
  hidden_size: 128
  betas: [0.0001, 0.02]
  num_timesteps: 1000
train_params:
  learning_rate: 0.00001
  epochs: 100
  batch_size: 128
  num_workers: 4
  optimizer: "adam"
  momentum: 0.0
augs:
  rand_flip: False